name: Run Python Script with API Key

# Define the event that triggers this workflow
on: 
  push:  # Trigger this workflow on a push to the main branch
    branches:
      - main  # You can change to any branch you want

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use a Ubuntu runner (you can choose another)

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run the Python script, passing the API key from GitHub Secrets
      - name: Run Python Script with API Key
        run: python scripts.py  # Run the script from the 'scripts' folder
        env:
          API_KEY: ${{ secrets.TEST_SECRET }}  # Pass the secret API key to the script
